### ISSUE TITLE
Local LLM support

### ISSUE THREAD

**Issue by mishushakov** [mishushakov/llm-scraper#1]
We want to also support local LLMs with functions calling

**Comment by mintisan** [comment]
like Ollama API wit base url

**Comment by mishushakov** [comment]
The problem is that Ollama currently doesn't support function calling and grammars. Until then, I'm working on a solution based on `node-llama-cpp`, which does in fact support it

**Comment by mishushakov** [comment]
have something working already

<img width="935" alt="Screenshot 2024-04-21 at 16 52 04" src="https://github.com/mishushakov/llm-scraper/assets/10400064/5864ea2b-9226-4f7b-98b1-1949f6417542">

**Comment by mishushakov** [comment]
This is now supported (see readme)
