### ISSUE TITLE
Can you click on links to extract content from the  detail item?

### ISSUE THREAD

**Issue by giannik** [mishushakov/llm-scraper#11]
this is a cool project . 
say you have a list of resumes and each resume has a link for more detail .
can you extract the content from the detail link and attach the content to the main  resume object ?
Thanks

**Comment by mishushakov** [comment]
This will be possible soon. I will let you updated

**Comment by mishushakov** [comment]
This is now possible, you can just action the page as you wish and then provide to llm scraper to scrape
