### ISSUE TITLE
Help tweak example to use groq llama 70b  (rec for tool use on their doc page)

### ISSUE THREAD

**Issue by jay377** [mishushakov/llm-scraper#24]
Hi, this is really awesome was looking for this and almost forced to do it myself somehow, definitely starred

Sorry must ask as total noob and non coder, the example code seems to use openAI and i just dont know enough how to edit it to use groq llama7b insead instead, there seems to be multiple places the model is mentioned in example groq has openai metioned in the same line and its all very confusing lol and just not quite sure how to edit it correctly. Would you mind showing whats needed to make it work? Thanks!

**Comment by mishushakov** [comment]
Follow the instructions provided in readme
