### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by mishushakov** [mishushakov/llm-scraper#4]
Support local models hosted with ollama

**Comment by eznix86** [comment]
This can be useful:
https://sdk.vercel.ai/providers/community-providers/ollama

**Comment by mishushakov** [comment]
Have you tried it? Does it work with generateObject?

**Comment by eznix86** [comment]
I didn't, but from the docs, it is possible: https://github.com/sgomez/ollama-ai-provider?tab=readme-ov-file#tested-models-and-capabilities
