### ISSUE TITLE
Example execution commands

### ISSUE THREAD

**Issue by strawberrymelonpanda** [mishushakov/llm-scraper#6]
I'm not a typescript dev, so I struggled a bit with how to actually execute the code shown in the Readme.md and the /examples folder.

I eventually ended up with

```
npx playwright install
npx tsx examples/local.ts
```

(editing the model path)  
Not sure if this is the best way.

**Comment by mishushakov** [comment]
Will make a more detailed readme on this soon. TypeScript is not a requirement though 😄

**Comment by gunar** [comment]
Using `npx tsx` didn't work for me:

```
ERROR: Top-level await is currently not supported with the "cjs" output format
```

Wondering how to run this project :)

**Comment by mishushakov** [comment]
You should switch your project to ESM modules
