### ISSUE TITLE
Local GPU use / Use local server

### ISSUE THREAD

**Issue by strawberrymelonpanda** [mishushakov/llm-scraper#7]
Unfortunately, it looks like node-llama-cpp doesn't support GPU without making a new build and changing some execution settings, so it's too slow for me to be practical.

Can we instead use OpenAI compatible servers like offered by Llama.cpp, oobabooga, and others?
At a glance, I couldn't see where I would change the OpenAI URL.  [Llama.cpp's server](https://github.com/ggerganov/llama.cpp/tree/master/examples/server) has support for grammar, but I'm not sure about functions.

**Comment by mishushakov** [comment]
Works well on my M1 machine, I haven't had to re-build it. What would be interesting is supporting multiple approaches for querying the model (prompt-based, grammar-based, function-calling). Also thinking about adding Ollama (with json mode).

You can change the URL like that:

```ts
const llm = new OpenAI({ baseUrl: 'http://localhost' })

// Create a new LLMScraper
const scraper = new LLMScraper(browser, llm)
```

**Comment by strawberrymelonpanda** [comment]
Thanks for the info.  The rebuilding is for [CUDA support](https://withcatai.github.io/node-llama-cpp/guide/CUDA), to my understanding.  I'm on Win11 with a 3090.

Using CPU, tiny models like phi-2 3B work well enough on CPU.
